export default {
  htmlLang: "en",
  base: "",
  meta: {
    description: "Open-source tools for debugging and improving Spryker search relevance. Understand Elasticsearch and OpenSearch scores, normalize business signals, and build explainable product ranking.",
    ogUrl: "https://search-relevance.dev/",
    ogImageAlt: "Search Relevance — the ranking formula: alpha times score over score plus k, plus one minus alpha times the sum of weighted business signals.",
    canonical: "https://search-relevance.dev/",
  },
  skipLink: "Skip to formula explorer",
  brand: { ariaLabel: "Search Relevance home" },
  nav: { ariaLabel: "Primary navigation", formula: "Formula", resources: "Resources" },
  langSwitch: { ariaLabel: "Language" },
  hero: {
    eyebrow: "Open-source Spryker search tools",
    title: "Explainable, tunable search relevance for Spryker.",
    liveBadge: "✓ Search Ranking v1",
    upcomingBadge: "🚧 Search Ranking v2 · OpenSearch 3.x",
    copy: "Debug and improve product ranking in Spryker with transparent scoring for Elasticsearch and OpenSearch.",
  },
  formulaExplorer: {
    ariaLabel: "Formula explorer",
    label: "finalScore =",
    ariaLabelFull: "final score equals alpha times score divided by score plus k, plus one minus alpha times the sum of weighted signals",
    summary: "Normalized text relevance + normalized business signals.",
    specLabelPrefix: "Then, query specificity shifts",
    specLabelSuffix: "→",
    specAriaLabelFull: "effective alpha equals alpha plus m times the sign of d times the absolute value of d to the power of gamma",
    dAriaLabelFull: "d equals 2 times specificity to the power of p, divided by specificity to the power of p plus k sub spec to the power of p, minus 1",
    specificityAriaLabelFull: "specificity equals beta times the maximum of the log of catalog size divided by documents containing the term, plus one minus beta times the harmonic mean of the log of catalog size divided by documents containing the term",
    specificityCatalogSize: "catalog size",
    specificityDocsContainingTerm: "documents containing the term",
  },
  stepNav: {
    ariaLabel: "Formula explanation steps",
    steps: ["Overview", "Elasticsearch relevance", "Saturation point", "Ranking signals", "Signal weights"],
    specificityToggle: "Query Specificity",
    optimizationToggle: "Optimization",
  },
  specCrumbs: {
    ariaLabel: "Query specificity steps",
    items: ["Analyze Query Terms", "Raw Specificity", "Normalize", "Shift the Balance", "Calibrate"],
  },
  optCrumbs: {
    ariaLabel: "Automated optimization steps",
    items: ["Relevance Dataset", "Rank Eval", "CMA-ES", "Optimal Parameters", "Adaptive Formula"],
  },
  optimizationCards: [
    {
      id: "optimization-dataset",
      index: "1 / 5",
      title: "Relevance Dataset",
      lead: "Every optimization starts with a representative collection of search queries and manually judged search results.",
      body: [
        "Each query is associated with products and their expected relevance. The quality of the optimized formula depends directly on the quality and diversity of this dataset — it should cover common searches, edge cases and business-critical queries.",
      ],
      tag: "The dataset is independent from the optimization algorithm and can continuously evolve as the shop changes.",
      visual: {
        kind: "dataset",
        productName: "Laser Printer",
        price: "$89.00",
        rateHeart: "Love it",
        rateCheck: "Relevant",
        rateX: "Not relevant",
        adminFlag: "Visible to admins",
        monitorTitle: "4K Monitor",
        laptopTitle: "Ultrabook Laptop",
        moreText: "+ 2 more judged results for this query",
      },
    },
    {
      id: "optimization-rank-eval",
      index: "2 / 5",
      title: "Rank Evaluation",
      lead: "Rank Eval replays every query from the dataset against the current formula and compares the returned order to the expected judgments.",
      body: [
        "Elasticsearch/OpenSearch Rank Eval executes every query of the relevance dataset using the current scoring formula. Metrics such as nDCG quantify how well the current parameter set performs across the entire dataset.",
      ],
      tag: "Rank Eval provides the objective fitness value that drives the optimizer.",
      visual: {
        kind: "rank-eval",
        expectedLabel: "Expected",
        actualLabel: "Actual",
        firstRowMismatch: false,
        printerTitle: "Laser Printer",
        monitorTitle: "4K Monitor",
        laptopTitle: "Ultrabook Laptop",
        ndcg: "nDCG = 0.87",
      },
    },
    {
      id: "optimization-cmaes",
      index: "3 / 5",
      title: "CMA-ES Optimizer",
      lead: "Covariance Matrix Adaptation Evolution Strategy searches for an optimal parameter set without requiring derivatives or manual tuning.",
      body: [
        "Multiple parameter candidates are evaluated using Rank Eval each generation. Better candidates survive, influence the next generation, and the search distribution shrinks and reorients as it converges toward the optimum.",
      ],
      tag: "Unlike manual trial-and-error, CMA-ES explores the complete parameter space automatically.",
      visual: {
        kind: "cmaes",
        ariaLabel: "Search distribution ellipses shrinking and reorienting across generations toward the optimum",
        param1: "parameter 1",
        param2: "parameter 2",
      },
    },
    {
      id: "optimization-parameters",
      index: "4 / 5",
      title: "Optimal Parameters",
      lead: "After the optimization completes, the best performing parameter set becomes the new runtime configuration for the adaptive scoring formula.",
      body: [
        "Typical optimized values include the specificity exponent, text weight, business signal weights, and the maximum specificity shift — the same symbols used throughout this formula.",
      ],
      tag: "Optimization happens offline. Runtime searches only use the resulting parameter set and remain deterministic and fast.",
      visual: {
        kind: "params",
        rows: [
          { name: "α", small: "text weight", before: "0.73", after: "0.62" },
          { name: "w", sub: "ctr", small: "click-through rate", before: "0.45", after: "0.38" },
          { name: "w", sub: "conv", small: "conversion rate", before: "0.30", after: "0.41" },
          { name: "γ", small: "specificity exponent", before: "1.0", after: "1.4" },
          { name: "m", small: "max specificity shift", before: "0.25", after: "0.18" },
        ],
      },
    },
    {
      id: "optimization-runtime",
      index: "5 / 5",
      title: "Adaptive Formula",
      lead: "The optimized parameters are loaded by the runtime search engine and applied to every query — deterministically, with no optimizer involved at request time.",
      body: [
        "Query specificity dynamically balances textual relevance and business signals while preserving a fully explainable ranking. Whenever the catalog or business priorities change, the optimization process can simply run again to produce a new parameter set.",
      ],
      tag: "Runtime ranking and offline optimization are intentionally separated. Search requests never execute the optimizer.",
      visual: {
        kind: "rank-eval",
        expectedLabel: "Before",
        actualLabel: "After",
        firstRowMismatch: true,
        printerTitle: "Laser Printer",
        monitorTitle: "4K Monitor",
        laptopTitle: "Ultrabook Laptop",
        ndcg: "nDCG = 1.0",
      },
    },
  ],
  specificityCards: [
    {
      id: "specificity-terms",
      index: "1 / 5",
      title: "Analyze Query Terms",
      lead: "Every matched term is looked up in the index's own term statistics — how many documents contain it, out of how many total.",
      body: [
        "A term that appears in almost every product (<code>chair</code>) carries little information about intent. A term that appears in almost none (<code>gsr</code>) is strong evidence the customer knows exactly what they want. A term with zero real matches anywhere in the catalog is skipped entirely, not treated as maximally rare.",
      ],
      tag: "idf<sub>term</sub> = log(catalog size / documents containing the term)",
      visual: {
        kind: "terms",
        heading: "Analyze Query",
        rows: [
          ["chair", "df 58", "idf 0.30"],
          ["bosch", "df 17", "idf 1.51"],
          ["gsr", "df 2", "idf 3.75"],
          ["18v", "df 2", "idf 3.75"],
        ],
        caption: "Rare terms carry far more discriminating power than common catalog terms.",
      },
    },
    {
      id: "specificity-raw",
      index: "2 / 5",
      title: "Blend into Raw Specificity",
      lead: "A query's per-term scores are combined into one number — weighted toward whichever term carries the strongest evidence.",
      body: [
        "The harmonic mean of every term's idf is pulled down hard the moment even one term is common, while the blend weight β lets the single rarest term still dominate when it's a strong enough signal on its own. A single-term query skips the blend — its own idf <em>is</em> the raw specificity.",
      ],
      tag: "specificity = β · max(idf) + (1 − β) · harmonicMean(idf)",
      visual: {
        kind: "raw-specificity",
        maxIdfLabel: "max(idf)",
        maxIdfValue: "3.75",
        hmeanLabel: "harmonic mean",
        hmeanValue: "1.03",
        betaLabel: "β",
        betaValue: "0.6",
        resultLabel: "raw specificity",
        resultValue: "2.66",
        equation: "\"Bosch GSR 18V-55\" → 2.66",
      },
    },
    {
      id: "specificity-normalize",
      index: "3 / 5",
      title: "Normalize — the same curve, again",
      lead: "Raw specificity is squashed through the exact same saturating shape used for Elasticsearch relevance — <strong>x / (x + k)</strong> — just with its own saturation point.",
      body: [
        "A curve exponent p can additionally steepen or soften the transition around the saturation point. It defaults to 1, which collapses back to the plain, unshaped ratio — the identical formula from step 2 of the main explorer, applied to a second signal.",
      ],
      tag: "normalize(x) = x<sup>p</sup> / (x<sup>p</sup> + k<sub>spec</sub><sup>p</sup>)",
      visual: {
        kind: "curve",
        ariaLabel: "Saturation curve applied to raw specificity",
        xAxisLabel: "raw specificity",
        kSpecLabel: "k_spec",
        equation: "specificity / (specificity + k_spec)",
      },
    },
    {
      id: "specificity-shift",
      index: "4 / 5",
      title: "Shift the Balance",
      lead: "Normalized specificity becomes a signed deviation from neutral, shaped and scaled into a nudge on α.",
      body: [
        "<strong>d = 2 · normalize(specificity) − 1</strong> centers a typical query at exactly zero. The exponent γ shapes how sensitively the shift reacts near that center — dampened for small deviations when γ &gt; 1, amplified when γ &lt; 1 — and the magnitude m caps how far specificity alone can ever move α, in either direction.",
      ],
      tag: "α<sub>eff</sub> = α + m · sign(d) · |d|<sup>γ</sup>",
      visual: {
        kind: "shift",
        heading: "Adaptive Weighting",
        specificLabel: "Specific",
        specificText: "Text 85%",
        specificBusiness: "Business 15%",
        genericLabel: "Generic",
        genericText: "Text 40%",
        genericBusiness: "Business 60%",
        caption: "The result stays deterministic and fully explainable for every single query.",
      },
    },
    {
      id: "specificity-calibrate",
      index: "5 / 5",
      title: "Calibrate the Parameters",
      lead: "k<sub>spec</sub>, β, p, γ and m aren't hand-tuned guesses — they're calibrated the same way the rest of the formula is.",
      body: [
        "Search Ranking Optimizer's saturation-point calibration has a dedicated specificity mode: it samples real queries and suggests k<sub>spec</sub> directly from their observed distribution. The remaining shift parameters are part of the same parameter space the automated optimizer already searches — see Optimization above.",
      ],
      tag: "Same calibration + optimization pipeline, applied to specificity's own parameters.",
      visual: {
        kind: "params",
        rows: [
          { name: "k", sub: "spec", small: "specificity saturation point", before: "guessed", after: "calibrated" },
          { name: "β", small: "blend weight", before: "0.5", after: "0.6" },
          { name: "γ", small: "shift exponent", before: "1.0", after: "1.4" },
          { name: "m", small: "max shift magnitude", before: "0.25", after: "0.18" },
        ],
      },
    },
  ],
  stepPanels: [
    {
      id: "step-panel-1",
      count: "01 / 05",
      titleId: "step-title-1",
      title: "How a result gets its score",
      lead: "Every hit is a convex combination of normalized text relevance and a weighted sum of business signals.",
      body: [
        "The model has exactly two terms. <strong>α</strong> decides how much influence text relevance receives; <strong>1 − α</strong> gives the remaining influence to business signals.",
        "Because both terms are normalized, their contributions remain comparable and the final score stays interpretable.",
      ],
      implementation: "Implemented by Search Ranking · explained by Search Debug",
    },
    {
      id: "step-panel-2",
      count: "02 / 05",
      titleId: "step-title-2",
      title: "Normalize Elasticsearch relevance",
      lead: "Elasticsearch's unbounded <code>_score</code> is squashed into a stable range from zero up to—but never reaching—one.",
      body: [
        "The transformation preserves the ordering of results while preventing large raw scores from overwhelming every other signal.",
        "It uses the same saturation shape that BM25 applies to term frequency, here applied to the complete document score.",
      ],
      implementation: "score / (score + k)",
    },
    {
      id: "step-panel-3",
      count: "03 / 05",
      titleId: "step-title-3",
      title: "Choose the saturation point",
      lead: "The parameter k controls where normalized relevance reaches exactly 0.5.",
      body: [
        "When <strong>score = k</strong>, the relevance term equals <strong>0.5</strong>. Lower values saturate earlier; higher values preserve more differentiation between large Elasticsearch scores.",
        "Rather than choosing <strong>k</strong> by guesswork, Search Ranking can estimate a practical starting point from representative searches. Import a CSV of typical queries and define the depth to inspect; the package executes the set, samples the highest-ranked results, analyzes their raw <code>_score</code> values, and recommends the observed mean as the initial saturation point.",
      ],
      implementation: "Representative queries + sampling depth → observed _score distribution → suggested k",
    },
    {
      id: "step-panel-4",
      count: "04 / 05",
      titleId: "step-title-4",
      title: "Add normalized business signals",
      lead: "The second term combines product-level signals such as click-through rate, conversion rate, availability, or margin.",
      body: [
        "Each metric is transformed into a value between zero and one before it enters the formula. This makes signals with very different units comparable.",
        "Search Ranking derives an <strong>aggregate frequency distribution</strong> from the metric data and evaluates the available normalization functions against that observed shape. The analysis view presents the empirical distribution beside the fitted curve and recommends the closest match; the selected expression remains fully configurable.",
        "A low-weight <strong>random()</strong> signal is also worth including in the business term. It breaks deterministic ties, introduces controlled variation, and prevents the same products from becoming permanently locked into identical positions.",
      ],
      implementation: "Distribution analysis → normalization-function suggestion · low-weight random() for controlled variation",
    },
    {
      id: "step-panel-5",
      count: "05 / 05",
      titleId: "step-title-5",
      title: "Keep signal weights comparable",
      lead: "Entered signal weights are force-normalized so their sum always equals one.",
      body: [
        "Editors can express relative importance without manually maintaining a perfect total. A weight of 30 and a weight of 10 become 0.75 and 0.25.",
        "This normalization runs once when configuration is published, keeping the query itself simple.",
      ],
      implementation: "w<sub>i</sub> = enteredWeight<sub>i</sub> / Σ enteredWeight<sub>j</sub>",
    },
  ],
  resources: {
    heading: "Resources",
    rows: [
      {
        small: "Bundle",
        title: "Search Toolkit",
        desc: "One composer require for the six packages below — Blackbox Optimizer comes along transitively through Search Optimization, not as a direct require.",
        href: "https://github.com/andrebarthelmeshellmuth/spryker-search-toolkit",
        githubAriaLabel: "View Search Toolkit on GitHub",
      },
      {
        small: "Feedback",
        title: "Search Feedback",
        desc: "Let an authorized storefront admin file a ticket about a set of search results.",
        href: "https://github.com/andrebarthelmeshellmuth/spryker-search-feedback",
        githubAriaLabel: "View Search Feedback on GitHub",
        screenshotsAnchor: "search-feedback",
      },
      {
        small: "Explanation",
        title: "Search Debug",
        desc: "Inspect how every term contributes to a result.",
        href: "https://github.com/andrebarthelmeshellmuth/spryker-search-debug",
        githubAriaLabel: "View Search Debug on GitHub",
        screenshotsAnchor: "search-debug",
      },
      {
        small: "Implementation",
        title: "Search Ranking",
        desc: "Configure and calculate the transparent ranking formula.",
        href: "https://github.com/andrebarthelmeshellmuth/spryker-search-ranking",
        githubAriaLabel: "View Search Ranking on GitHub",
        screenshotsAnchor: "search-ranking",
      },
      {
        small: "Optimization",
        title: "Search Optimization",
        desc: "Learn ranking parameters from weighted human relevance judgments.",
        href: "https://github.com/andrebarthelmeshellmuth/spryker-search-ranking-optimizer",
        githubAriaLabel: "View Search Optimization on GitHub",
        screenshotsAnchor: "search-optimization",
      },
      {
        small: "Facets",
        title: "Search Variant Facets",
        desc: "Fixes cross-facet AND correctness for product variants, so combining facets like color and size only returns products that actually exist in that combination.",
        href: "https://github.com/andrebarthelmeshellmuth/spryker-search-variant-facets",
        githubAriaLabel: "View Search Variant Facets on GitHub",
        screenshotsAnchor: "search-variant-facets",
      },
      {
        small: "Indexing",
        title: "Search Index Alias",
        desc: "Zero-downtime blue-green rebuilds behind a stable alias — build a new index in the background, verify it, then flip atomically.",
        href: "https://github.com/andrebarthelmeshellmuth/spryker-search-index-alias",
        githubAriaLabel: "View Search Index Alias on GitHub",
        screenshotsAnchor: "search-index-alias",
      },
      {
        small: "Analyzer",
        title: "Search Analyzer Config",
        desc: "A separate composer require: stage analyzer knobs — stemming, synonyms, decompounding — from a Zed GUI, safely materialized into Search Index Alias's next rebuild.",
        href: "https://github.com/andrebarthelmeshellmuth/spryker-search-analyzer-config",
        githubAriaLabel: "View Search Analyzer Config on GitHub",
        screenshotsAnchor: "search-analyzer-config",
      },
      {
        small: "Dependency",
        title: "Blackbox Optimizer",
        desc: "The optimization engine Search Optimization is built on — usable in any PHP project.",
        href: "https://github.com/andrebarthelmeshellmuth/blackbox-optimizer",
        githubAriaLabel: "View Blackbox Optimizer on GitHub",
      },
    ],
    screenshotsText: "Screenshots",
    diagram: {
      titleText: "Dependencies between the Search Relevance packages",
      descText: "Search Toolkit is one composer require that pulls in all six packages below it. Search Feedback, Search Debug, Search Ranking, Search Variant Facets, and Search Index Alias have no dependencies of their own. Search Debug can optionally read Search Ranking's data. Search Optimization requires Search Ranking and delegates its optimization work to Blackbox Optimizer, which has no Spryker dependency and is also usable in any PHP project. Search Analyzer Config is a separate composer require, outside the toolkit bundle, that itself requires Search Index Alias.",
      optionalLabel: "optional",
      requiresLabel: "requires",
      delegatesLabel: "delegates to",
      alsoUsesLabel: "also uses",
      toolkitTitle: "Search Toolkit",
      toolkitSub: "one composer require",
      feedbackTitle: "Search Feedback",
      noDeps: "no dependencies",
      debugTitle: "Search Debug",
      rankingTitle: "Search Ranking",
      optimizationTitle: "Search Optimization",
      optimizationSub: "tunes Ranking's weights",
      variantFacetsTitle: "Search Variant Facets",
      indexAliasTitle: "Search Index Alias",
      blackboxTitle: "Blackbox Optimizer",
      blackboxSub: "the optimization engine",
      analyzerConfigTitle: "Search Analyzer Config",
      analyzerConfigSub: "separate composer require",
      ghostTitle: "any PHP project",
      ghostSub: "no Spryker dependency",
      figcaption: "Solid arrows are hard requirements; dashed arrows are optional or go outside this toolkit entirely.",
    },
  },
  roadmap: {
    heading: "Roadmap",
    paragraphs: [
      "Search Relevance v1 targets the capabilities available in OpenSearch 1.3, which has been the default for Spryker installations for several years.",
      "With Spryker now enabling OpenSearch 3.x, a new generation of ranking features becomes practical. Search Relevance v2 will explore reranking, hybrid retrieval, Learning-to-Rank and other capabilities that previously weren't available.",
    ],
  },
  origins: {
    heading: "Origins",
    paragraph1Pre: "This project's starting point is Spryker's own",
    paragraph1LinkText: "Data-driven ranking",
    paragraph1Post: "best-practice document — which itself documents a real system, not a Spryker invention: the ranking approach originally designed and implemented by Martin Loetsch and Krešimir Slugan at Contorion. Spryker's core never shipped an implementation of it, only the write-up.",
    paragraph2: "search-ranking and search-ranking-optimizer are that idea built out and adapted for Spryker's actual plugin/facade architecture, then extended well past the original scope — locale/store scoping, specificity-aware relevance weighting, and automated black-box optimization among them.",
  },
  footer: {
    builtByPre: "Built by André Barthelmes-Hellmuth",
    linkedinAriaLabel: "André Barthelmes-Hellmuth on LinkedIn",
    license: "MIT licensed",
    homeHref: "https://search-relevance.dev/",
    homeText: "search-relevance.dev",
  },
  screenshots: {
    meta: {
      description: "Screenshots of the Spryker Search Relevance tools: Search Feedback, Search Debug, Search Ranking and Search Optimization.",
      ogUrl: "https://search-relevance.dev/screenshots.html",
      canonical: "https://search-relevance.dev/screenshots.html",
    },
    skipLink: "Skip to screenshots",
    hero: {
      eyebrow: "Open-source Spryker search tools",
      title: "See it in action.",
      copy: "A tour of each package's Zed and Yves surfaces. Pick a package below, then a screenshot.",
    },
    packageSelectorAriaLabel: "Package selection",
    carousel: { prevLabel: "Previous screenshot", nextLabel: "Next screenshot" },
    galleryAriaLabel: "Screenshot gallery",
  },
};
